name: ngoerahsun # Ubah jadi huruf kecil (snake_case)
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.9.1
  flutter_svg: ^2.2.0
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.1.0
  toastification: ^3.0.3

  # Logic & Utilities
  get: ^4.7.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  intl_utils: ^2.8.12
  readmore: ^3.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  url_launcher: ^6.3.2

  # Input & Forms
  intl_phone_field: ^3.2.0
  calendar_date_picker2: ^2.0.1
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4

  # Network & Firebase
  dio: ^5.4.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  syncfusion_flutter_pdfviewer: ^31.1.19
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  onesignal_flutter: ^5.3.4
  # google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Tools
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0
  # flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700