name: Ngoerahsun
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  loading_indicator: ^3.1.1
  readmore: ^3.0.0
  calendar_date_picker2: ^2.0.1
  flutter_svg: ^2.0.9
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2

  # ðŸ”½ FIXED: compatible dengan Dart 3.4.x
  intl: ^0.19.0

  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0

  # ðŸ”½ FIXED FIREBASE VERSIONS
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1

  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_pdfviewer: ^29.1.35
  dio: ^5.4.0
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  permission_handler: ^11.3.1
  onesignal_flutter: ^5.2.6
  image_picker: ^1.0.7
  toastification: ^2.0.0
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  get: ^4.6.6
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/icons/
